apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gsp
stringData:
  ACCESS_KEY_ID: INSERT_GSP_ACCESS_KEY
  SECRET_ACCESS_KEY: INSERT_GSP_SECRET
  BUCKET_HOST: storage.googleapis.com
  BUCKET_NAME: INSERT_VGSPSTORAGEBUCKET
  BUCKET_PORT: "443"
  KAFKA_ADDR: kafka-helm-cp-kafka.kafka.svc.cluster.local